### ISSUE TITLE
Elm in IoT

### ISSUE THREAD

**Issue by unixbigot** [elmbrisbane/meetup#3]
As a speaker and advocate on security and best practices in the Internet of Things, I see so many products that are awful in regard to setup, usability and security.

I have dozens of IoT device setup apps on my phone.  No more!

Let me show you how I use a no-pain wifi "captive portal" and Elm to provide elegant and portable setup and user interfaces for my IoT devices.

Elm, being remarkably self-contained is well suited to IoT applications, but corralling all the external resources (stylesheets, fonts etc) can be a challenge.   I'll show you my process for building and deploying applications to embedded internet-capable devices.

**Comment by Maxim-Filimonov** [comment]
Great use-cause for Elm @unixbigot . Looking forward to your talk !

**Comment by Maxim-Filimonov** [comment]
Slides - http://christopher.biggs.id.au/talk/2018-11-22-elm-for-iot/

**Comment by Maxim-Filimonov** [comment]
Let's try again 
Video - https://www.youtube.com/watch?v=JDhVhpI7Wyo
