### ISSUE TITLE
Elm in Minecraft

### ISSUE THREAD

**Issue by jwulf** [elmbrisbane/meetup#4]
Since Elm transpiles to JavaScript, and I have a "Programming with JavaScript in Minecraft" platform, I thought I'd give programming in Minecraft in Elm a go.

Elm is a purely functional language, and Minecraft is very much a mutations via side-effects environment - kind of like a web-browser where you are not the only thing mutating the DOM.

I took inspiration from a recent Elmconf talk on robotics programming in Elm. I'll share the mixed results I got, and what I learned along the way.

**Comment by Maxim-Filimonov** [comment]
Video recording - https://www.youtube.com/watch?v=KI6Rm-jzJ5c

**Comment by Maxim-Filimonov** [comment]
Video - https://www.youtube.com/watch?v=yu_o5nNOpHQ
